### ISSUE TITLE
Resources/config\services.yml - InvalidArgumentException

### ISSUE THREAD

**Issue by skocdopolet** [dfridrich/DefrAresBundle#1]
Missing quotation marks near `@kernel`

```
services:
    defr_ares:
        class: 'Defr\AresBundle\Service\AresService'
        arguments: ["@kernel"]
```
